services:
  postgres:
    image: postgres:16
    container_name: edge_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: edge_pipeline
    volumes:
      - /home/vraj/edge-db/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Exposes the DB to the host machine (and Tailscale)
    deploy:
      resources:
        limits:
          memory: 3G # Prevents edge data from starving the AI models of RAM
